torchrun --redirects 1:0,2:0,3:0,4:0,5:0,6:0,7:0 --standalone --nnodes=1 --nproc_per_node=8 submission_runner.py --framework=pytorch --workload=librispeech_conformer --submission_path=submissions_algorithms/submissions/self_tuning/schedule_free_adamw_v2/submission.py --data_dir=/data/librispeech --num_tuning_trials=1 --experiment_dir=/experiment_runs --experiment_name=submissions/rolling_leaderboard/self_tuning/schedule_free_adamw_v2/study_0 --overwrite=True --save_checkpoints=False --rng_seed=-1464714999 --librispeech_tokenizer_vocab_path=/data/librispeech/spm_model.vocab --torch_compile=true --tuning_ruleset=self 2>&1 | tee -a /logs/librispeech_conformer_pytorch_03-18-2025-15-54-08.log
W0318 15:54:10.109000 9 site-packages/torch/distributed/run.py:793] 
W0318 15:54:10.109000 9 site-packages/torch/distributed/run.py:793] *****************************************
W0318 15:54:10.109000 9 site-packages/torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0318 15:54:10.109000 9 site-packages/torch/distributed/run.py:793] *****************************************
2025-03-18 15:54:11.102107: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-03-18 15:54:11.102107: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-03-18 15:54:11.102105: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-03-18 15:54:11.102105: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-03-18 15:54:11.102107: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-03-18 15:54:11.102105: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-03-18 15:54:11.102105: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-03-18 15:54:11.102569: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1742313251.122921      50 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1742313251.122918      46 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1742313251.122925      48 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1742313251.122919      47 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1742313251.122919      45 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1742313251.122918      44 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1742313251.122919      49 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1742313251.124164      51 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1742313251.129078      47 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
E0000 00:00:1742313251.129085      49 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
E0000 00:00:1742313251.129085      44 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
E0000 00:00:1742313251.129084      45 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
E0000 00:00:1742313251.129090      46 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
E0000 00:00:1742313251.129087      50 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
E0000 00:00:1742313251.129091      48 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
E0000 00:00:1742313251.130605      51 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
ERROR:root:Unable to import wandb.
Traceback (most recent call last):
  File "/algorithmic-efficiency/algoperf/logger_utils.py", line 27, in <module>
    import wandb  # pylint: disable=g-import-not-at-top
    ^^^^^^^^^^^^
ModuleNotFoundError: No module named 'wandb'
ERROR:root:Unable to import wandb.
Traceback (most recent call last):
  File "/algorithmic-efficiency/algoperf/logger_utils.py", line 27, in <module>
    import wandb  # pylint: disable=g-import-not-at-top
    ^^^^^^^^^^^^
ModuleNotFoundError: No module named 'wandb'
[W318 15:54:17.450812721 CUDAAllocatorConfig.h:28] Warning: expandable_segments not supported on this platform (function operator())
ERROR:root:Unable to import wandb.
Traceback (most recent call last):
  File "/algorithmic-efficiency/algoperf/logger_utils.py", line 27, in <module>
    import wandb  # pylint: disable=g-import-not-at-top
    ^^^^^^^^^^^^
ModuleNotFoundError: No module named 'wandb'
ERROR:root:Unable to import wandb.
Traceback (most recent call last):
  File "/algorithmic-efficiency/algoperf/logger_utils.py", line 27, in <module>
    import wandb  # pylint: disable=g-import-not-at-top
    ^^^^^^^^^^^^
ModuleNotFoundError: No module named 'wandb'
ERROR:root:Unable to import wandb.
Traceback (most recent call last):
  File "/algorithmic-efficiency/algoperf/logger_utils.py", line 27, in <module>
    import wandb  # pylint: disable=g-import-not-at-top
    ^^^^^^^^^^^^
ModuleNotFoundError: No module named 'wandb'
ERROR:root:Unable to import wandb.
Traceback (most recent call last):
  File "/algorithmic-efficiency/algoperf/logger_utils.py", line 27, in <module>
    import wandb  # pylint: disable=g-import-not-at-top
    ^^^^^^^^^^^^
ModuleNotFoundError: No module named 'wandb'
ERROR:root:Unable to import wandb.
Traceback (most recent call last):
  File "/algorithmic-efficiency/algoperf/logger_utils.py", line 27, in <module>
    import wandb  # pylint: disable=g-import-not-at-top
    ^^^^^^^^^^^^
ModuleNotFoundError: No module named 'wandb'
ERROR:root:Unable to import wandb.
Traceback (most recent call last):
  File "/algorithmic-efficiency/algoperf/logger_utils.py", line 27, in <module>
    import wandb  # pylint: disable=g-import-not-at-top
    ^^^^^^^^^^^^
ModuleNotFoundError: No module named 'wandb'
[W318 15:54:18.133797203 CUDAAllocatorConfig.h:28] Warning: expandable_segments not supported on this platform (function operator())
[W318 15:54:18.133900284 CUDAAllocatorConfig.h:28] Warning: expandable_segments not supported on this platform (function operator())
[W318 15:54:18.143336845 CUDAAllocatorConfig.h:28] Warning: expandable_segments not supported on this platform (function operator())
[W318 15:54:18.156527395 CUDAAllocatorConfig.h:28] Warning: expandable_segments not supported on this platform (function operator())
[W318 15:54:18.191182038 CUDAAllocatorConfig.h:28] Warning: expandable_segments not supported on this platform (function operator())
[rank0]:[W318 15:54:18.193953777 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 0]  using GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank4]:[W318 15:54:18.250206432 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 4]  using GPU 4 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank7]:[W318 15:54:18.250617563 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 7]  using GPU 7 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank1]:[W318 15:54:18.257473936 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 1]  using GPU 1 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[W318 15:54:18.261310417 CUDAAllocatorConfig.h:28] Warning: expandable_segments not supported on this platform (function operator())
[rank6]:[W318 15:54:18.273257434 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 6]  using GPU 6 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[W318 15:54:18.296244737 CUDAAllocatorConfig.h:28] Warning: expandable_segments not supported on this platform (function operator())
[rank5]:[W318 15:54:18.307609748 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 5]  using GPU 5 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank2]:[W318 15:54:18.376505326 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 2]  using GPU 2 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank3]:[W318 15:54:18.411304321 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 3]  using GPU 3 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
I0318 15:54:20.118954 139951561499840 logger_utils.py:81] Creating experiment directory at /experiment_runs/submissions/rolling_leaderboard/self_tuning/schedule_free_adamw_v2/study_0/librispeech_conformer_pytorch.
I0318 15:54:20.118954 140697046877376 logger_utils.py:81] Creating experiment directory at /experiment_runs/submissions/rolling_leaderboard/self_tuning/schedule_free_adamw_v2/study_0/librispeech_conformer_pytorch.
I0318 15:54:20.118954 139806343365824 logger_utils.py:81] Creating experiment directory at /experiment_runs/submissions/rolling_leaderboard/self_tuning/schedule_free_adamw_v2/study_0/librispeech_conformer_pytorch.
I0318 15:54:20.118954 140122018346176 logger_utils.py:81] Creating experiment directory at /experiment_runs/submissions/rolling_leaderboard/self_tuning/schedule_free_adamw_v2/study_0/librispeech_conformer_pytorch.
I0318 15:54:20.118954 139814479172800 logger_utils.py:81] Creating experiment directory at /experiment_runs/submissions/rolling_leaderboard/self_tuning/schedule_free_adamw_v2/study_0/librispeech_conformer_pytorch.
I0318 15:54:20.118956 140704340255936 logger_utils.py:81] Creating experiment directory at /experiment_runs/submissions/rolling_leaderboard/self_tuning/schedule_free_adamw_v2/study_0/librispeech_conformer_pytorch.
I0318 15:54:20.118965 139649795105984 logger_utils.py:81] Creating experiment directory at /experiment_runs/submissions/rolling_leaderboard/self_tuning/schedule_free_adamw_v2/study_0/librispeech_conformer_pytorch.
I0318 15:54:20.119077 139814151378112 logger_utils.py:81] Creating experiment directory at /experiment_runs/submissions/rolling_leaderboard/self_tuning/schedule_free_adamw_v2/study_0/librispeech_conformer_pytorch.
I0318 15:54:20.164493 139649795105984 submission_runner.py:665] Creating directory at /experiment_runs/submissions/rolling_leaderboard/self_tuning/schedule_free_adamw_v2/study_0/librispeech_conformer_pytorch/trial_1.
I0318 15:54:20.464794 139649795105984 submission_runner.py:218] Initializing dataset.
I0318 15:54:20.464986 139649795105984 input_pipeline.py:20] Loading split = train-clean-100
I0318 15:54:20.514010 139649795105984 input_pipeline.py:20] Loading split = train-clean-360
I0318 15:54:20.633130 139649795105984 input_pipeline.py:20] Loading split = train-other-500
I0318 15:54:21.119138 139649795105984 submission_runner.py:229] Initializing model.
W0318 15:54:22.825224 140704340255936 submission_runner.py:254] These workloads cannot be fully compiled under current PyTorch version. Proceeding without `torch.compile`.
W0318 15:54:22.825285 139951561499840 submission_runner.py:254] These workloads cannot be fully compiled under current PyTorch version. Proceeding without `torch.compile`.
I0318 15:54:22.826344 139951561499840 logger_utils.py:262] Unable to record workload.train_mean information. Continuing without it.
I0318 15:54:22.826344 140704340255936 logger_utils.py:262] Unable to record workload.train_mean information. Continuing without it.
I0318 15:54:22.826429 140704340255936 logger_utils.py:262] Unable to record workload.train_stddev information. Continuing without it.
I0318 15:54:22.826442 139951561499840 logger_utils.py:262] Unable to record workload.train_stddev information. Continuing without it.
W0318 15:54:22.827974 139806343365824 submission_runner.py:254] These workloads cannot be fully compiled under current PyTorch version. Proceeding without `torch.compile`.
W0318 15:54:22.828610 140697046877376 submission_runner.py:254] These workloads cannot be fully compiled under current PyTorch version. Proceeding without `torch.compile`.
I0318 15:54:22.829070 139806343365824 logger_utils.py:262] Unable to record workload.train_mean information. Continuing without it.
I0318 15:54:22.829173 139806343365824 logger_utils.py:262] Unable to record workload.train_stddev information. Continuing without it.
I0318 15:54:22.829673 140697046877376 logger_utils.py:262] Unable to record workload.train_mean information. Continuing without it.
I0318 15:54:22.829798 140697046877376 logger_utils.py:262] Unable to record workload.train_stddev information. Continuing without it.
W0318 15:54:22.830463 139814479172800 submission_runner.py:254] These workloads cannot be fully compiled under current PyTorch version. Proceeding without `torch.compile`.
W0318 15:54:22.831100 139649795105984 submission_runner.py:254] These workloads cannot be fully compiled under current PyTorch version. Proceeding without `torch.compile`.
I0318 15:54:22.831239 139649795105984 submission_runner.py:272] Initializing optimizer.
W0318 15:54:22.831270 139814151378112 submission_runner.py:254] These workloads cannot be fully compiled under current PyTorch version. Proceeding without `torch.compile`.
I0318 15:54:22.831586 139814479172800 logger_utils.py:262] Unable to record workload.train_mean information. Continuing without it.
I0318 15:54:22.831684 139814479172800 logger_utils.py:262] Unable to record workload.train_stddev information. Continuing without it.
I0318 15:54:22.831933 139649795105984 submission_runner.py:279] Initializing metrics bundle.
I0318 15:54:22.832064 139649795105984 submission_runner.py:301] Initializing checkpoint and logger.
I0318 15:54:22.832261 139649795105984 submission_runner.py:321] Saving meta data to /experiment_runs/submissions/rolling_leaderboard/self_tuning/schedule_free_adamw_v2/study_0/librispeech_conformer_pytorch/trial_1/meta_data_0.json.
I0318 15:54:22.832464 139649795105984 logger_utils.py:262] Unable to record workload.train_mean information. Continuing without it.
I0318 15:54:22.832441 139814151378112 logger_utils.py:262] Unable to record workload.train_mean information. Continuing without it.
I0318 15:54:22.832515 139649795105984 logger_utils.py:262] Unable to record workload.train_stddev information. Continuing without it.
I0318 15:54:22.832544 139814151378112 logger_utils.py:262] Unable to record workload.train_stddev information. Continuing without it.
W0318 15:54:22.838102 140122018346176 submission_runner.py:254] These workloads cannot be fully compiled under current PyTorch version. Proceeding without `torch.compile`.
I0318 15:54:22.839308 140122018346176 logger_utils.py:262] Unable to record workload.train_mean information. Continuing without it.
I0318 15:54:22.839408 140122018346176 logger_utils.py:262] Unable to record workload.train_stddev information. Continuing without it.
I0318 15:54:23.156970 139649795105984 submission_runner.py:325] Saving flags to /experiment_runs/submissions/rolling_leaderboard/self_tuning/schedule_free_adamw_v2/study_0/librispeech_conformer_pytorch/trial_1/flags_0.json.
I0318 15:54:23.161334 139649795105984 submission_runner.py:337] Starting training loop.
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0318 15:54:32.785069 139649795105984 spec.py:321] Evaluating on the training split.
I0318 15:54:32.786065 139649795105984 input_pipeline.py:20] Loading split = train-clean-100
I0318 15:54:32.814087 139649795105984 input_pipeline.py:20] Loading split = train-clean-360
I0318 15:54:32.911313 139649795105984 input_pipeline.py:20] Loading split = train-other-500
I0318 15:55:06.743594 139649795105984 spec.py:333] Evaluating on the validation split.
I0318 15:55:06.744642 139649795105984 input_pipeline.py:20] Loading split = dev-clean
I0318 15:55:06.795542 139649795105984 input_pipeline.py:20] Loading split = dev-other
I0318 15:55:26.814221 139649795105984 spec.py:349] Evaluating on the test split.
I0318 15:55:26.815389 139649795105984 input_pipeline.py:20] Loading split = test-clean
I0318 15:55:37.135210 139649795105984 submission_runner.py:469] Time since start: 73.97s, 	Step: 1, 	{'train/ctc_loss': 31.57973683499135, 'train/wer': 1.7138588032389455, 'validation/ctc_loss': 30.602701368184857, 'validation/wer': 1.8218413556703519, 'validation/num_examples': 5348, 'test/ctc_loss': 30.581820165026244, 'test/wer': 1.8557877846160096, 'test/num_examples': 2472, 'score': 8.635170459747314, 'total_duration': 73.97373175621033, 'accumulated_submission_time': 8.635170459747314, 'accumulated_eval_time': 64.35000848770142, 'accumulated_logging_time': 0}
I0318 15:55:37.148140 139629739087616 logging_writer.py:48] [1] accumulated_eval_time=64.35, accumulated_logging_time=0, accumulated_submission_time=8.63517, global_step=1, preemption_count=0, score=8.63517, test/ctc_loss=30.5818, test/num_examples=2472, test/wer=1.85579, total_duration=73.9737, train/ctc_loss=31.5797, train/wer=1.71386, validation/ctc_loss=30.6027, validation/num_examples=5348, validation/wer=1.82184
I0318 16:19:38.400533 139649795105984 spec.py:321] Evaluating on the training split.
I0318 16:19:49.755650 139649795105984 spec.py:333] Evaluating on the validation split.
I0318 16:20:09.702396 139649795105984 spec.py:349] Evaluating on the test split.
I0318 16:20:19.892706 139649795105984 submission_runner.py:469] Time since start: 1556.73s, 	Step: 2061, 	{'train/ctc_loss': 3.5277923267192905, 'train/wer': 0.7045736816700202, 'validation/ctc_loss': 3.743781759201965, 'validation/wer': 0.6913725679524936, 'validation/num_examples': 5348, 'test/ctc_loss': 3.4756972070014243, 'test/wer': 0.6638027339386184, 'test/num_examples': 2472, 'score': 1447.1233897209167, 'total_duration': 1556.7312588691711, 'accumulated_submission_time': 1447.1233897209167, 'accumulated_eval_time': 105.84203553199768, 'accumulated_logging_time': 0.04183554649353027}
I0318 16:20:19.922072 139629739087616 logging_writer.py:48] [2061] accumulated_eval_time=105.842, accumulated_logging_time=0.0418355, accumulated_submission_time=1447.12, global_step=2061, preemption_count=0, score=1447.12, test/ctc_loss=3.4757, test/num_examples=2472, test/wer=0.663803, total_duration=1556.73, train/ctc_loss=3.52779, train/wer=0.704574, validation/ctc_loss=3.74378, validation/num_examples=5348, validation/wer=0.691373
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0318 16:44:21.434626 139649795105984 spec.py:321] Evaluating on the training split.
I0318 16:44:35.567741 139649795105984 spec.py:333] Evaluating on the validation split.
I0318 16:44:56.018213 139649795105984 spec.py:349] Evaluating on the test split.
I0318 16:45:06.480701 139649795105984 submission_runner.py:469] Time since start: 3043.32s, 	Step: 4387, 	{'train/ctc_loss': 1.6799510705017302, 'train/wer': 0.43354250166774233, 'validation/ctc_loss': 1.8986647072059402, 'validation/wer': 0.4425626418191474, 'validation/num_examples': 5348, 'test/ctc_loss': 1.5488056931487162, 'test/wer': 0.39794446814128737, 'test/num_examples': 2472, 'score': 2885.457167863846, 'total_duration': 3043.3191623687744, 'accumulated_submission_time': 2885.457167863846, 'accumulated_eval_time': 150.88802099227905, 'accumulated_logging_time': 0.09502053260803223}
I0318 16:45:06.534233 139629739087616 logging_writer.py:48] [4387] accumulated_eval_time=150.888, accumulated_logging_time=0.0950205, accumulated_submission_time=2885.46, global_step=4387, preemption_count=0, score=2885.46, test/ctc_loss=1.54881, test/num_examples=2472, test/wer=0.397944, total_duration=3043.32, train/ctc_loss=1.67995, train/wer=0.433543, validation/ctc_loss=1.89866, validation/num_examples=5348, validation/wer=0.442563
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0318 17:09:08.243477 139649795105984 spec.py:321] Evaluating on the training split.
I0318 17:09:22.682292 139649795105984 spec.py:333] Evaluating on the validation split.
I0318 17:09:42.447299 139649795105984 spec.py:349] Evaluating on the test split.
I0318 17:09:52.849328 139649795105984 submission_runner.py:469] Time since start: 4529.69s, 	Step: 6724, 	{'train/ctc_loss': 0.8932230068325584, 'train/wer': 0.2904149559878729, 'validation/ctc_loss': 1.084245287293819, 'validation/wer': 0.3192970598175059, 'validation/num_examples': 5348, 'test/ctc_loss': 0.7957805762925558, 'test/wer': 0.25704304023723923, 'test/num_examples': 2472, 'score': 4323.998267412186, 'total_duration': 4529.6879296302795, 'accumulated_submission_time': 4323.998267412186, 'accumulated_eval_time': 195.49387788772583, 'accumulated_logging_time': 0.15955758094787598}
I0318 17:09:52.976042 139629739087616 logging_writer.py:48] [6724] accumulated_eval_time=195.494, accumulated_logging_time=0.159558, accumulated_submission_time=4324, global_step=6724, preemption_count=0, score=4324, test/ctc_loss=0.795781, test/num_examples=2472, test/wer=0.257043, total_duration=4529.69, train/ctc_loss=0.893223, train/wer=0.290415, validation/ctc_loss=1.08425, validation/num_examples=5348, validation/wer=0.319297
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0318 17:33:54.052455 139649795105984 spec.py:321] Evaluating on the training split.
I0318 17:34:07.243017 139649795105984 spec.py:333] Evaluating on the validation split.
I0318 17:34:27.146815 139649795105984 spec.py:349] Evaluating on the test split.
I0318 17:34:37.359371 139649795105984 submission_runner.py:469] Time since start: 6014.20s, 	Step: 9064, 	{'train/ctc_loss': 0.624564570126649, 'train/wer': 0.21368796134091908, 'validation/ctc_loss': 0.8325144498509309, 'validation/wer': 0.2539467966977261, 'validation/num_examples': 5348, 'test/ctc_loss': 0.5680918720404995, 'test/wer': 0.19188349277923344, 'test/num_examples': 2472, 'score': 5761.835393190384, 'total_duration': 6014.19798707962, 'accumulated_submission_time': 5761.835393190384, 'accumulated_eval_time': 238.8008143901825, 'accumulated_logging_time': 0.4487488269805908}
I0318 17:34:37.448045 139629739087616 logging_writer.py:48] [9064] accumulated_eval_time=238.801, accumulated_logging_time=0.448749, accumulated_submission_time=5761.84, global_step=9064, preemption_count=0, score=5761.84, test/ctc_loss=0.568092, test/num_examples=2472, test/wer=0.191883, total_duration=6014.2, train/ctc_loss=0.624565, train/wer=0.213688, validation/ctc_loss=0.832514, validation/num_examples=5348, validation/wer=0.253947
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0318 17:58:38.621883 139649795105984 spec.py:321] Evaluating on the training split.
I0318 17:58:52.178883 139649795105984 spec.py:333] Evaluating on the validation split.
I0318 17:59:12.071920 139649795105984 spec.py:349] Evaluating on the test split.
I0318 17:59:22.350262 139649795105984 submission_runner.py:469] Time since start: 7499.19s, 	Step: 11390, 	{'train/ctc_loss': 0.492283487814933, 'train/wer': 0.1727998004132747, 'validation/ctc_loss': 0.7088452209627921, 'validation/wer': 0.2179983585188046, 'validation/num_examples': 5348, 'test/ctc_loss': 0.4590263563976542, 'test/wer': 0.15832876322791622, 'test/num_examples': 2472, 'score': 7199.8107080459595, 'total_duration': 7499.188824892044, 'accumulated_submission_time': 7199.8107080459595, 'accumulated_eval_time': 282.5291917324066, 'accumulated_logging_time': 0.5751423835754395}
I0318 17:59:22.503506 139629739087616 logging_writer.py:48] [11390] accumulated_eval_time=282.529, accumulated_logging_time=0.575142, accumulated_submission_time=7199.81, global_step=11390, preemption_count=0, score=7199.81, test/ctc_loss=0.459026, test/num_examples=2472, test/wer=0.158329, total_duration=7499.19, train/ctc_loss=0.492283, train/wer=0.1728, validation/ctc_loss=0.708845, validation/num_examples=5348, validation/wer=0.217998
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0318 18:23:24.340927 139649795105984 spec.py:321] Evaluating on the training split.
I0318 18:23:37.226364 139649795105984 spec.py:333] Evaluating on the validation split.
I0318 18:23:57.116881 139649795105984 spec.py:349] Evaluating on the test split.
I0318 18:24:07.410015 139649795105984 submission_runner.py:469] Time since start: 8984.25s, 	Step: 13697, 	{'train/ctc_loss': 0.41324644517733566, 'train/wer': 0.14642506548939424, 'validation/ctc_loss': 0.6362022479108461, 'validation/wer': 0.19403273306619032, 'validation/num_examples': 5348, 'test/ctc_loss': 0.3964026177945385, 'test/wer': 0.135782909836898, 'test/num_examples': 2472, 'score': 8638.36709022522, 'total_duration': 8984.248577356339, 'accumulated_submission_time': 8638.36709022522, 'accumulated_eval_time': 325.59833574295044, 'accumulated_logging_time': 0.8677687644958496}
I0318 18:24:07.519009 139629739087616 logging_writer.py:48] [13697] accumulated_eval_time=325.598, accumulated_logging_time=0.867769, accumulated_submission_time=8638.37, global_step=13697, preemption_count=0, score=8638.37, test/ctc_loss=0.396403, test/num_examples=2472, test/wer=0.135783, total_duration=8984.25, train/ctc_loss=0.413246, train/wer=0.146425, validation/ctc_loss=0.636202, validation/num_examples=5348, validation/wer=0.194033
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0318 18:48:09.477925 139649795105984 spec.py:321] Evaluating on the training split.
I0318 18:48:31.611348 139649795105984 spec.py:333] Evaluating on the validation split.
I0318 18:48:51.473140 139649795105984 spec.py:349] Evaluating on the test split.
I0318 18:49:01.937052 139649795105984 submission_runner.py:469] Time since start: 10478.78s, 	Step: 15995, 	{'train/ctc_loss': 0.3600585831902844, 'train/wer': 0.12844056600191994, 'validation/ctc_loss': 0.5808177935909696, 'validation/wer': 0.17630473615603728, 'validation/num_examples': 5348, 'test/ctc_loss': 0.35443475444165695, 'test/wer': 0.1210773261836573, 'test/num_examples': 2472, 'score': 10076.551731586456, 'total_duration': 10478.775567531586, 'accumulated_submission_time': 10076.551731586456, 'accumulated_eval_time': 378.05740547180176, 'accumulated_logging_time': 1.1733660697937012}
I0318 18:49:02.069043 139629739087616 logging_writer.py:48] [15995] accumulated_eval_time=378.057, accumulated_logging_time=1.17337, accumulated_submission_time=10076.6, global_step=15995, preemption_count=0, score=10076.6, test/ctc_loss=0.354435, test/num_examples=2472, test/wer=0.121077, total_duration=10478.8, train/ctc_loss=0.360059, train/wer=0.128441, validation/ctc_loss=0.580818, validation/num_examples=5348, validation/wer=0.176305
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0318 19:13:04.425528 139649795105984 spec.py:321] Evaluating on the training split.
I0318 19:13:21.982183 139649795105984 spec.py:333] Evaluating on the validation split.
I0318 19:13:41.972486 139649795105984 spec.py:349] Evaluating on the test split.
I0318 19:13:52.244680 139649795105984 submission_runner.py:469] Time since start: 11969.08s, 	Step: 18292, 	{'train/ctc_loss': 0.32603420270768, 'train/wer': 0.11682331693612683, 'validation/ctc_loss': 0.5473354693642847, 'validation/wer': 0.16602133925554, 'validation/num_examples': 5348, 'test/ctc_loss': 0.32858479029251736, 'test/wer': 0.11224178904393395, 'test/num_examples': 2472, 'score': 11515.596170902252, 'total_duration': 11969.083227396011, 'accumulated_submission_time': 11515.596170902252, 'accumulated_eval_time': 425.8766071796417, 'accumulated_logging_time': 1.4528858661651611}
I0318 19:13:52.392499 139629739087616 logging_writer.py:48] [18292] accumulated_eval_time=425.877, accumulated_logging_time=1.45289, accumulated_submission_time=11515.6, global_step=18292, preemption_count=0, score=11515.6, test/ctc_loss=0.328585, test/num_examples=2472, test/wer=0.112242, total_duration=11969.1, train/ctc_loss=0.326034, train/wer=0.116823, validation/ctc_loss=0.547335, validation/num_examples=5348, validation/wer=0.166021
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0318 19:37:54.393166 139649795105984 spec.py:321] Evaluating on the training split.
I0318 19:38:10.106800 139649795105984 spec.py:333] Evaluating on the validation split.
I0318 19:38:30.019238 139649795105984 spec.py:349] Evaluating on the test split.
I0318 19:38:40.397208 139649795105984 submission_runner.py:469] Time since start: 13457.24s, 	Step: 20581, 	{'train/ctc_loss': 0.3009002051963938, 'train/wer': 0.10833003400567304, 'validation/ctc_loss': 0.5209862697117998, 'validation/wer': 0.15778496596340463, 'validation/num_examples': 5348, 'test/ctc_loss': 0.3085685110343655, 'test/wer': 0.10549834460626002, 'test/num_examples': 2472, 'score': 12953.980468034744, 'total_duration': 13457.23568367958, 'accumulated_submission_time': 12953.980468034744, 'accumulated_eval_time': 471.88055992126465, 'accumulated_logging_time': 1.7536473274230957}
I0318 19:38:40.533146 139629739087616 logging_writer.py:48] [20581] accumulated_eval_time=471.881, accumulated_logging_time=1.75365, accumulated_submission_time=12954, global_step=20581, preemption_count=0, score=12954, test/ctc_loss=0.308569, test/num_examples=2472, test/wer=0.105498, total_duration=13457.2, train/ctc_loss=0.3009, train/wer=0.10833, validation/ctc_loss=0.520986, validation/num_examples=5348, validation/wer=0.157785
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0318 20:02:41.850089 139649795105984 spec.py:321] Evaluating on the training split.
I0318 20:02:56.954507 139649795105984 spec.py:333] Evaluating on the validation split.
I0318 20:03:17.054138 139649795105984 spec.py:349] Evaluating on the test split.
I0318 20:03:27.304985 139649795105984 submission_runner.py:469] Time since start: 14944.14s, 	Step: 22915, 	{'train/ctc_loss': 0.28258342808918147, 'train/wer': 0.10146381677070848, 'validation/ctc_loss': 0.5007124335127162, 'validation/wer': 0.15061072756240043, 'validation/num_examples': 5348, 'test/ctc_loss': 0.29605003420669346, 'test/wer': 0.09940487071679564, 'test/num_examples': 2472, 'score': 14392.055718421936, 'total_duration': 14944.143404960632, 'accumulated_submission_time': 14392.055718421936, 'accumulated_eval_time': 517.335221529007, 'accumulated_logging_time': 2.0441057682037354}
I0318 20:03:27.417529 139629739087616 logging_writer.py:48] [22915] accumulated_eval_time=517.335, accumulated_logging_time=2.04411, accumulated_submission_time=14392.1, global_step=22915, preemption_count=0, score=14392.1, test/ctc_loss=0.29605, test/num_examples=2472, test/wer=0.0994049, total_duration=14944.1, train/ctc_loss=0.282583, train/wer=0.101464, validation/ctc_loss=0.500712, validation/num_examples=5348, validation/wer=0.150611
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0318 20:27:28.510576 139649795105984 spec.py:321] Evaluating on the training split.
I0318 20:27:43.657918 139649795105984 spec.py:333] Evaluating on the validation split.
I0318 20:28:03.756061 139649795105984 spec.py:349] Evaluating on the test split.
I0318 20:28:14.101203 139649795105984 submission_runner.py:469] Time since start: 16430.94s, 	Step: 25253, 	{'train/ctc_loss': 0.26837955461653873, 'train/wer': 0.09647414863787483, 'validation/ctc_loss': 0.48412205924634205, 'validation/wer': 0.14495244532419255, 'validation/num_examples': 5348, 'test/ctc_loss': 0.2846874117764061, 'test/wer': 0.0950175695163813, 'test/num_examples': 2472, 'score': 15829.901205778122, 'total_duration': 16430.93974494934, 'accumulated_submission_time': 15829.901205778122, 'accumulated_eval_time': 562.9257946014404, 'accumulated_logging_time': 2.288867235183716}
I0318 20:28:14.285546 139629739087616 logging_writer.py:48] [25253] accumulated_eval_time=562.926, accumulated_logging_time=2.28887, accumulated_submission_time=15829.9, global_step=25253, preemption_count=0, score=15829.9, test/ctc_loss=0.284687, test/num_examples=2472, test/wer=0.0950176, total_duration=16430.9, train/ctc_loss=0.26838, train/wer=0.0964741, validation/ctc_loss=0.484122, validation/num_examples=5348, validation/wer=0.144952
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0318 20:52:15.621226 139649795105984 spec.py:321] Evaluating on the training split.
I0318 20:52:28.729895 139649795105984 spec.py:333] Evaluating on the validation split.
I0318 20:52:48.726539 139649795105984 spec.py:349] Evaluating on the test split.
I0318 20:52:59.062214 139649795105984 submission_runner.py:469] Time since start: 17915.90s, 	Step: 27596, 	{'train/ctc_loss': 0.2567425368153925, 'train/wer': 0.0922925898004675, 'validation/ctc_loss': 0.4720108360209509, 'validation/wer': 0.14109013662917008, 'validation/num_examples': 5348, 'test/ctc_loss': 0.2764716146601948, 'test/wer': 0.09168647045680743, 'test/num_examples': 2472, 'score': 17267.866627931595, 'total_duration': 17915.900733947754, 'accumulated_submission_time': 17267.866627931595, 'accumulated_eval_time': 606.3667330741882, 'accumulated_logging_time': 2.595789670944214}
I0318 20:52:59.172421 139629739087616 logging_writer.py:48] [27596] accumulated_eval_time=606.367, accumulated_logging_time=2.59579, accumulated_submission_time=17267.9, global_step=27596, preemption_count=0, score=17267.9, test/ctc_loss=0.276472, test/num_examples=2472, test/wer=0.0916865, total_duration=17915.9, train/ctc_loss=0.256743, train/wer=0.0922926, validation/ctc_loss=0.472011, validation/num_examples=5348, validation/wer=0.14109
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0318 21:17:00.421420 139649795105984 spec.py:321] Evaluating on the training split.
I0318 21:17:14.315986 139649795105984 spec.py:333] Evaluating on the validation split.
I0318 21:17:34.302125 139649795105984 spec.py:349] Evaluating on the test split.
I0318 21:17:44.567429 139649795105984 submission_runner.py:469] Time since start: 19401.41s, 	Step: 29924, 	{'train/ctc_loss': 0.24679330476015085, 'train/wer': 0.08869135106111802, 'validation/ctc_loss': 0.46075560727656834, 'validation/wer': 0.1380292569883648, 'validation/num_examples': 5348, 'test/ctc_loss': 0.2692916427393586, 'test/wer': 0.0889240956269169, 'test/num_examples': 2472, 'score': 18705.85681629181, 'total_duration': 19401.405910491943, 'accumulated_submission_time': 18705.85681629181, 'accumulated_eval_time': 650.5126616954803, 'accumulated_logging_time': 2.8151562213897705}
I0318 21:17:44.716468 139629739087616 logging_writer.py:48] [29924] accumulated_eval_time=650.513, accumulated_logging_time=2.81516, accumulated_submission_time=18705.9, global_step=29924, preemption_count=0, score=18705.9, test/ctc_loss=0.269292, test/num_examples=2472, test/wer=0.0889241, total_duration=19401.4, train/ctc_loss=0.246793, train/wer=0.0886914, validation/ctc_loss=0.460756, validation/num_examples=5348, validation/wer=0.138029
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0318 21:41:46.998468 139649795105984 spec.py:321] Evaluating on the training split.
I0318 21:41:59.488063 139649795105984 spec.py:333] Evaluating on the validation split.
I0318 21:42:19.390703 139649795105984 spec.py:349] Evaluating on the test split.
I0318 21:42:29.673086 139649795105984 submission_runner.py:469] Time since start: 20886.51s, 	Step: 32233, 	{'train/ctc_loss': 0.23721015164596398, 'train/wer': 0.08536128993768338, 'validation/ctc_loss': 0.449722751542255, 'validation/wer': 0.13592429874957757, 'validation/num_examples': 5348, 'test/ctc_loss': 0.2628367334171725, 'test/wer': 0.08729916925639307, 'test/num_examples': 2472, 'score': 20144.837346076965, 'total_duration': 20886.51160788536, 'accumulated_submission_time': 20144.837346076965, 'accumulated_eval_time': 693.1871786117554, 'accumulated_logging_time': 3.1301040649414062}
I0318 21:42:29.807168 139629739087616 logging_writer.py:48] [32233] accumulated_eval_time=693.187, accumulated_logging_time=3.1301, accumulated_submission_time=20144.8, global_step=32233, preemption_count=0, score=20144.8, test/ctc_loss=0.262837, test/num_examples=2472, test/wer=0.0872992, total_duration=20886.5, train/ctc_loss=0.23721, train/wer=0.0853613, validation/ctc_loss=0.449723, validation/num_examples=5348, validation/wer=0.135924
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0318 22:06:31.385493 139649795105984 spec.py:321] Evaluating on the training split.
I0318 22:06:53.727652 139649795105984 spec.py:333] Evaluating on the validation split.
I0318 22:07:13.922402 139649795105984 spec.py:349] Evaluating on the test split.
I0318 22:07:24.299335 139649795105984 submission_runner.py:469] Time since start: 22381.14s, 	Step: 34531, 	{'train/ctc_loss': 0.22843816948596993, 'train/wer': 0.08230240643016364, 'validation/ctc_loss': 0.44052742737182254, 'validation/wer': 0.1333172403804374, 'validation/num_examples': 5348, 'test/ctc_loss': 0.2564043311368332, 'test/wer': 0.08504458391729125, 'test/num_examples': 2472, 'score': 21582.680775880814, 'total_duration': 22381.13790512085, 'accumulated_submission_time': 21582.680775880814, 'accumulated_eval_time': 746.1010415554047, 'accumulated_logging_time': 3.411498546600342}
I0318 22:07:24.441838 139629739087616 logging_writer.py:48] [34531] accumulated_eval_time=746.101, accumulated_logging_time=3.4115, accumulated_submission_time=21582.7, global_step=34531, preemption_count=0, score=21582.7, test/ctc_loss=0.256404, test/num_examples=2472, test/wer=0.0850446, total_duration=22381.1, train/ctc_loss=0.228438, train/wer=0.0823024, validation/ctc_loss=0.440527, validation/num_examples=5348, validation/wer=0.133317
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0318 22:31:26.262801 139649795105984 spec.py:321] Evaluating on the training split.
I0318 22:31:43.614491 139649795105984 spec.py:333] Evaluating on the validation split.
I0318 22:32:03.894427 139649795105984 spec.py:349] Evaluating on the test split.
I0318 22:32:14.356191 139649795105984 submission_runner.py:469] Time since start: 23871.19s, 	Step: 36825, 	{'train/ctc_loss': 0.22038052568798658, 'train/wer': 0.07975333684056383, 'validation/ctc_loss': 0.4320635316857612, 'validation/wer': 0.13000531067445564, 'validation/num_examples': 5348, 'test/ctc_loss': 0.2510924938163281, 'test/wer': 0.08441492494871326, 'test/num_examples': 2472, 'score': 23021.127812623978, 'total_duration': 23871.19474720955, 'accumulated_submission_time': 23021.127812623978, 'accumulated_eval_time': 794.1945281028748, 'accumulated_logging_time': 3.726175546646118}
I0318 22:32:14.425875 139629739087616 logging_writer.py:48] [36825] accumulated_eval_time=794.195, accumulated_logging_time=3.72618, accumulated_submission_time=23021.1, global_step=36825, preemption_count=0, score=23021.1, test/ctc_loss=0.251092, test/num_examples=2472, test/wer=0.0844149, total_duration=23871.2, train/ctc_loss=0.220381, train/wer=0.0797533, validation/ctc_loss=0.432064, validation/num_examples=5348, validation/wer=0.130005
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0318 22:56:16.035730 139649795105984 spec.py:321] Evaluating on the training split.
I0318 22:56:31.812429 139649795105984 spec.py:333] Evaluating on the validation split.
I0318 22:56:51.889891 139649795105984 spec.py:349] Evaluating on the test split.
I0318 22:57:02.365082 139649795105984 submission_runner.py:469] Time since start: 25359.20s, 	Step: 39112, 	{'train/ctc_loss': 0.21256058108847858, 'train/wer': 0.07639073440321942, 'validation/ctc_loss': 0.4230291520566525, 'validation/wer': 0.1267223482836866, 'validation/num_examples': 5348, 'test/ctc_loss': 0.24562243048782836, 'test/wer': 0.0816728616984543, 'test/num_examples': 2472, 'score': 24459.17872595787, 'total_duration': 25359.203690052032, 'accumulated_submission_time': 24459.17872595787, 'accumulated_eval_time': 840.5239961147308, 'accumulated_logging_time': 3.9158380031585693}
I0318 22:57:02.521154 139629739087616 logging_writer.py:48] [39112] accumulated_eval_time=840.524, accumulated_logging_time=3.91584, accumulated_submission_time=24459.2, global_step=39112, preemption_count=0, score=24459.2, test/ctc_loss=0.245622, test/num_examples=2472, test/wer=0.0816729, total_duration=25359.2, train/ctc_loss=0.212561, train/wer=0.0763907, validation/ctc_loss=0.423029, validation/num_examples=5348, validation/wer=0.126722
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0318 23:21:03.708185 139649795105984 spec.py:321] Evaluating on the training split.
I0318 23:21:18.718040 139649795105984 spec.py:333] Evaluating on the validation split.
I0318 23:21:38.822126 139649795105984 spec.py:349] Evaluating on the test split.
I0318 23:21:49.169519 139649795105984 submission_runner.py:469] Time since start: 26846.01s, 	Step: 41441, 	{'train/ctc_loss': 0.20444324849798606, 'train/wer': 0.07397725362157706, 'validation/ctc_loss': 0.41328316902927004, 'validation/wer': 0.12387389562110751, 'validation/num_examples': 5348, 'test/ctc_loss': 0.23951237015091048, 'test/wer': 0.07917453740377389, 'test/num_examples': 2472, 'score': 25896.997721672058, 'total_duration': 26846.008023500443, 'accumulated_submission_time': 25896.997721672058, 'accumulated_eval_time': 885.9853148460388, 'accumulated_logging_time': 4.243177890777588}
I0318 23:21:49.283169 139629739087616 logging_writer.py:48] [41441] accumulated_eval_time=885.985, accumulated_logging_time=4.24318, accumulated_submission_time=25897, global_step=41441, preemption_count=0, score=25897, test/ctc_loss=0.239512, test/num_examples=2472, test/wer=0.0791745, total_duration=26846, train/ctc_loss=0.204443, train/wer=0.0739773, validation/ctc_loss=0.413283, validation/num_examples=5348, validation/wer=0.123874
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0318 23:45:50.696660 139649795105984 spec.py:321] Evaluating on the training split.
I0318 23:46:05.195866 139649795105984 spec.py:333] Evaluating on the validation split.
I0318 23:46:25.261247 139649795105984 spec.py:349] Evaluating on the test split.
I0318 23:46:35.600756 139649795105984 submission_runner.py:469] Time since start: 28332.44s, 	Step: 43778, 	{'train/ctc_loss': 0.197351211495053, 'train/wer': 0.0717861384849849, 'validation/ctc_loss': 0.4036822362931503, 'validation/wer': 0.1206199005455511, 'validation/num_examples': 5348, 'test/ctc_loss': 0.23525365185526198, 'test/wer': 0.07738711839619768, 'test/num_examples': 2472, 'score': 27335.13751411438, 'total_duration': 28332.43933081627, 'accumulated_submission_time': 27335.13751411438, 'accumulated_eval_time': 930.8893487453461, 'accumulated_logging_time': 4.490421295166016}
I0318 23:46:35.777982 139629739087616 logging_writer.py:48] [43778] accumulated_eval_time=930.889, accumulated_logging_time=4.49042, accumulated_submission_time=27335.1, global_step=43778, preemption_count=0, score=27335.1, test/ctc_loss=0.235254, test/num_examples=2472, test/wer=0.0773871, total_duration=28332.4, train/ctc_loss=0.197351, train/wer=0.0717861, validation/ctc_loss=0.403682, validation/num_examples=5348, validation/wer=0.12062
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 00:10:36.855668 139649795105984 spec.py:321] Evaluating on the training split.
I0319 00:10:50.255428 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 00:11:10.271266 139649795105984 spec.py:349] Evaluating on the test split.
I0319 00:11:20.517166 139649795105984 submission_runner.py:469] Time since start: 29817.36s, 	Step: 46118, 	{'train/ctc_loss': 0.1908950409674727, 'train/wer': 0.06899300904106172, 'validation/ctc_loss': 0.39619389598294924, 'validation/wer': 0.11853425385023898, 'validation/num_examples': 5348, 'test/ctc_loss': 0.23003891061506282, 'test/wer': 0.07669652468872504, 'test/num_examples': 2472, 'score': 28772.897924661636, 'total_duration': 29817.35569500923, 'accumulated_submission_time': 28772.897924661636, 'accumulated_eval_time': 974.5508449077606, 'accumulated_logging_time': 4.792465925216675}
I0319 00:11:20.657513 139629739087616 logging_writer.py:48] [46118] accumulated_eval_time=974.551, accumulated_logging_time=4.79247, accumulated_submission_time=28772.9, global_step=46118, preemption_count=0, score=28772.9, test/ctc_loss=0.230039, test/num_examples=2472, test/wer=0.0766965, total_duration=29817.4, train/ctc_loss=0.190895, train/wer=0.068993, validation/ctc_loss=0.396194, validation/num_examples=5348, validation/wer=0.118534
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 00:35:22.276437 139649795105984 spec.py:321] Evaluating on the training split.
I0319 00:35:36.028988 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 00:35:56.243050 139649795105984 spec.py:349] Evaluating on the test split.
I0319 00:36:06.523071 139649795105984 submission_runner.py:469] Time since start: 31303.36s, 	Step: 48452, 	{'train/ctc_loss': 0.18518678869755623, 'train/wer': 0.0669049413985172, 'validation/ctc_loss': 0.3884097419496478, 'validation/wer': 0.1158885723941486, 'validation/num_examples': 5348, 'test/ctc_loss': 0.22585846569545856, 'test/wer': 0.0740966424958869, 'test/num_examples': 2472, 'score': 30211.259391069412, 'total_duration': 31303.36152768135, 'accumulated_submission_time': 30211.259391069412, 'accumulated_eval_time': 1018.797486782074, 'accumulated_logging_time': 5.045107841491699}
I0319 00:36:06.650382 139629739087616 logging_writer.py:48] [48452] accumulated_eval_time=1018.8, accumulated_logging_time=5.04511, accumulated_submission_time=30211.3, global_step=48452, preemption_count=0, score=30211.3, test/ctc_loss=0.225858, test/num_examples=2472, test/wer=0.0740966, total_duration=31303.4, train/ctc_loss=0.185187, train/wer=0.0669049, validation/ctc_loss=0.38841, validation/num_examples=5348, validation/wer=0.115889
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 01:00:07.971690 139649795105984 spec.py:321] Evaluating on the training split.
I0319 01:00:20.996903 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 01:00:40.976447 139649795105984 spec.py:349] Evaluating on the test split.
I0319 01:00:51.276498 139649795105984 submission_runner.py:469] Time since start: 32788.12s, 	Step: 50760, 	{'train/ctc_loss': 0.1798431502081531, 'train/wer': 0.06498500387783991, 'validation/ctc_loss': 0.381449793897233, 'validation/wer': 0.11367740066624825, 'validation/num_examples': 5348, 'test/ctc_loss': 0.22100280952044862, 'test/wer': 0.07245140454573153, 'test/num_examples': 2472, 'score': 31649.286893606186, 'total_duration': 32788.115111112595, 'accumulated_submission_time': 31649.286893606186, 'accumulated_eval_time': 1062.1022925376892, 'accumulated_logging_time': 5.314641237258911}
I0319 01:00:51.351705 139629739087616 logging_writer.py:48] [50760] accumulated_eval_time=1062.1, accumulated_logging_time=5.31464, accumulated_submission_time=31649.3, global_step=50760, preemption_count=0, score=31649.3, test/ctc_loss=0.221003, test/num_examples=2472, test/wer=0.0724514, total_duration=32788.1, train/ctc_loss=0.179843, train/wer=0.064985, validation/ctc_loss=0.38145, validation/num_examples=5348, validation/wer=0.113677
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 01:24:53.560652 139649795105984 spec.py:321] Evaluating on the training split.
I0319 01:25:16.357592 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 01:25:36.433883 139649795105984 spec.py:349] Evaluating on the test split.
I0319 01:25:46.771452 139649795105984 submission_runner.py:469] Time since start: 34283.61s, 	Step: 53061, 	{'train/ctc_loss': 0.17443352669580586, 'train/wer': 0.06310845477570899, 'validation/ctc_loss': 0.37492563151200364, 'validation/wer': 0.11139863853618501, 'validation/num_examples': 5348, 'test/ctc_loss': 0.21627232056925072, 'test/wer': 0.07100928239189162, 'test/num_examples': 2472, 'score': 33087.846156835556, 'total_duration': 34283.60993671417, 'accumulated_submission_time': 33087.846156835556, 'accumulated_eval_time': 1115.3130116462708, 'accumulated_logging_time': 5.51361083984375}
I0319 01:25:46.927028 139629739087616 logging_writer.py:48] [53061] accumulated_eval_time=1115.31, accumulated_logging_time=5.51361, accumulated_submission_time=33087.8, global_step=53061, preemption_count=0, score=33087.8, test/ctc_loss=0.216272, test/num_examples=2472, test/wer=0.0710093, total_duration=34283.6, train/ctc_loss=0.174434, train/wer=0.0631085, validation/ctc_loss=0.374926, validation/num_examples=5348, validation/wer=0.111399
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 01:49:48.756154 139649795105984 spec.py:321] Evaluating on the training split.
I0319 01:50:06.753819 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 01:50:26.857610 139649795105984 spec.py:349] Evaluating on the test split.
I0319 01:50:37.192716 139649795105984 submission_runner.py:469] Time since start: 35774.03s, 	Step: 55355, 	{'train/ctc_loss': 0.1695781430571137, 'train/wer': 0.06078717438347769, 'validation/ctc_loss': 0.36972882212034275, 'validation/wer': 0.11034615941679139, 'validation/num_examples': 5348, 'test/ctc_loss': 0.2117544705301115, 'test/wer': 0.06907968232689456, 'test/num_examples': 2472, 'score': 34526.44637155533, 'total_duration': 35774.03126716614, 'accumulated_submission_time': 34526.44637155533, 'accumulated_eval_time': 1163.7495365142822, 'accumulated_logging_time': 5.736665487289429}
I0319 01:50:37.266668 139629739087616 logging_writer.py:48] [55355] accumulated_eval_time=1163.75, accumulated_logging_time=5.73667, accumulated_submission_time=34526.4, global_step=55355, preemption_count=0, score=34526.4, test/ctc_loss=0.211754, test/num_examples=2472, test/wer=0.0690797, total_duration=35774, train/ctc_loss=0.169578, train/wer=0.0607872, validation/ctc_loss=0.369729, validation/num_examples=5348, validation/wer=0.110346
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 02:14:39.126417 139649795105984 spec.py:321] Evaluating on the training split.
I0319 02:14:55.107646 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 02:15:15.257834 139649795105984 spec.py:349] Evaluating on the test split.
I0319 02:15:25.617081 139649795105984 submission_runner.py:469] Time since start: 37262.46s, 	Step: 57646, 	{'train/ctc_loss': 0.16528047079858482, 'train/wer': 0.05920349710653484, 'validation/ctc_loss': 0.3657982302350728, 'validation/wer': 0.10841500506928016, 'validation/num_examples': 5348, 'test/ctc_loss': 0.20785924847934606, 'test/wer': 0.06739382121747609, 'test/num_examples': 2472, 'score': 35964.750351428986, 'total_duration': 37262.45564484596, 'accumulated_submission_time': 35964.750351428986, 'accumulated_eval_time': 1210.2401645183563, 'accumulated_logging_time': 5.912116527557373}
I0319 02:15:25.690107 139629739087616 logging_writer.py:48] [57646] accumulated_eval_time=1210.24, accumulated_logging_time=5.91212, accumulated_submission_time=35964.8, global_step=57646, preemption_count=0, score=35964.8, test/ctc_loss=0.207859, test/num_examples=2472, test/wer=0.0673938, total_duration=37262.5, train/ctc_loss=0.16528, train/wer=0.0592035, validation/ctc_loss=0.365798, validation/num_examples=5348, validation/wer=0.108415
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 02:39:27.258580 139649795105984 spec.py:321] Evaluating on the training split.
I0319 02:39:42.248016 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 02:40:02.403141 139649795105984 spec.py:349] Evaluating on the test split.
I0319 02:40:12.735347 139649795105984 submission_runner.py:469] Time since start: 38749.57s, 	Step: 59970, 	{'train/ctc_loss': 0.16108766971574934, 'train/wer': 0.05778252639914091, 'validation/ctc_loss': 0.360801917896408, 'validation/wer': 0.10698595085212186, 'validation/num_examples': 5348, 'test/ctc_loss': 0.20472048108726756, 'test/wer': 0.0661751264395832, 'test/num_examples': 2472, 'score': 37403.02093601227, 'total_duration': 38749.57385778427, 'accumulated_submission_time': 37403.02093601227, 'accumulated_eval_time': 1255.7167463302612, 'accumulated_logging_time': 6.195309400558472}
I0319 02:40:12.865015 139629739087616 logging_writer.py:48] [59970] accumulated_eval_time=1255.72, accumulated_logging_time=6.19531, accumulated_submission_time=37403, global_step=59970, preemption_count=0, score=37403, test/ctc_loss=0.20472, test/num_examples=2472, test/wer=0.0661751, total_duration=38749.6, train/ctc_loss=0.161088, train/wer=0.0577825, validation/ctc_loss=0.360802, validation/num_examples=5348, validation/wer=0.106986
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 03:04:14.061412 139649795105984 spec.py:321] Evaluating on the training split.
I0319 03:04:28.735197 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 03:04:48.563601 139649795105984 spec.py:349] Evaluating on the test split.
I0319 03:04:59.010784 139649795105984 submission_runner.py:469] Time since start: 40235.85s, 	Step: 62310, 	{'train/ctc_loss': 0.15711287396176876, 'train/wer': 0.05661646265070696, 'validation/ctc_loss': 0.35561211564724704, 'validation/wer': 0.1057017332110269, 'validation/num_examples': 5348, 'test/ctc_loss': 0.2019664638058696, 'test/wer': 0.0647736274450064, 'test/num_examples': 2472, 'score': 38840.865753650665, 'total_duration': 40235.849303245544, 'accumulated_submission_time': 38840.865753650665, 'accumulated_eval_time': 1300.6660978794098, 'accumulated_logging_time': 6.47693133354187}
I0319 03:04:59.152671 139629739087616 logging_writer.py:48] [62310] accumulated_eval_time=1300.67, accumulated_logging_time=6.47693, accumulated_submission_time=38840.9, global_step=62310, preemption_count=0, score=38840.9, test/ctc_loss=0.201966, test/num_examples=2472, test/wer=0.0647736, total_duration=40235.8, train/ctc_loss=0.157113, train/wer=0.0566165, validation/ctc_loss=0.355612, validation/num_examples=5348, validation/wer=0.105702
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 03:29:00.644663 139649795105984 spec.py:321] Evaluating on the training split.
I0319 03:29:13.663700 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 03:29:33.573819 139649795105984 spec.py:349] Evaluating on the test split.
I0319 03:29:43.800839 139649795105984 submission_runner.py:469] Time since start: 41720.64s, 	Step: 64651, 	{'train/ctc_loss': 0.1535086978265571, 'train/wer': 0.05527684522808749, 'validation/ctc_loss': 0.35183978263892796, 'validation/wer': 0.1040699077873799, 'validation/num_examples': 5348, 'test/ctc_loss': 0.19939349286832547, 'test/wer': 0.06347368634858733, 'test/num_examples': 2472, 'score': 40278.97322964668, 'total_duration': 41720.639348745346, 'accumulated_submission_time': 40278.97322964668, 'accumulated_eval_time': 1343.8222811222076, 'accumulated_logging_time': 6.818136215209961}
I0319 03:29:43.920520 139629739087616 logging_writer.py:48] [64651] accumulated_eval_time=1343.82, accumulated_logging_time=6.81814, accumulated_submission_time=40279, global_step=64651, preemption_count=0, score=40279, test/ctc_loss=0.199393, test/num_examples=2472, test/wer=0.0634737, total_duration=41720.6, train/ctc_loss=0.153509, train/wer=0.0552768, validation/ctc_loss=0.35184, validation/num_examples=5348, validation/wer=0.10407
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 03:53:45.312833 139649795105984 spec.py:321] Evaluating on the training split.
I0319 03:53:59.549290 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 03:54:19.492800 139649795105984 spec.py:349] Evaluating on the test split.
I0319 03:54:29.851232 139649795105984 submission_runner.py:469] Time since start: 43206.69s, 	Step: 66987, 	{'train/ctc_loss': 0.14976818256312174, 'train/wer': 0.053714862160417834, 'validation/ctc_loss': 0.3489239812444919, 'validation/wer': 0.10234152464635736, 'validation/num_examples': 5348, 'test/ctc_loss': 0.1965884086629153, 'test/wer': 0.06308776633558792, 'test/num_examples': 2472, 'score': 41717.07803106308, 'total_duration': 43206.68977832794, 'accumulated_submission_time': 41717.07803106308, 'accumulated_eval_time': 1388.3607594966888, 'accumulated_logging_time': 7.078534364700317}
I0319 03:54:29.977621 139629739087616 logging_writer.py:48] [66987] accumulated_eval_time=1388.36, accumulated_logging_time=7.07853, accumulated_submission_time=41717.1, global_step=66987, preemption_count=0, score=41717.1, test/ctc_loss=0.196588, test/num_examples=2472, test/wer=0.0630878, total_duration=43206.7, train/ctc_loss=0.149768, train/wer=0.0537149, validation/ctc_loss=0.348924, validation/num_examples=5348, validation/wer=0.102342
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 04:18:31.318000 139649795105984 spec.py:321] Evaluating on the training split.
I0319 04:18:45.264437 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 04:19:05.356563 139649795105984 spec.py:349] Evaluating on the test split.
I0319 04:19:15.666753 139649795105984 submission_runner.py:469] Time since start: 44692.51s, 	Step: 69297, 	{'train/ctc_loss': 0.14653378126942987, 'train/wer': 0.05284167023717194, 'validation/ctc_loss': 0.34627821119517727, 'validation/wer': 0.1012987012987013, 'validation/num_examples': 5348, 'test/ctc_loss': 0.1943690965382666, 'test/wer': 0.06186907155769504, 'test/num_examples': 2472, 'score': 43155.031641960144, 'total_duration': 44692.50529932976, 'accumulated_submission_time': 43155.031641960144, 'accumulated_eval_time': 1432.709673166275, 'accumulated_logging_time': 7.325417757034302}
I0319 04:19:15.781842 139629739087616 logging_writer.py:48] [69297] accumulated_eval_time=1432.71, accumulated_logging_time=7.32542, accumulated_submission_time=43155, global_step=69297, preemption_count=0, score=43155, test/ctc_loss=0.194369, test/num_examples=2472, test/wer=0.0618691, total_duration=44692.5, train/ctc_loss=0.146534, train/wer=0.0528417, validation/ctc_loss=0.346278, validation/num_examples=5348, validation/wer=0.101299
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 04:43:17.501583 139649795105984 spec.py:321] Evaluating on the training split.
I0319 04:43:40.349320 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 04:44:00.599623 139649795105984 spec.py:349] Evaluating on the test split.
I0319 04:44:11.031823 139649795105984 submission_runner.py:469] Time since start: 46187.87s, 	Step: 71596, 	{'train/ctc_loss': 0.14377935864933633, 'train/wer': 0.051605100308600126, 'validation/ctc_loss': 0.3439340656700606, 'validation/wer': 0.10062279727707236, 'validation/num_examples': 5348, 'test/ctc_loss': 0.19159959000089827, 'test/wer': 0.06099567363353848, 'test/num_examples': 2472, 'score': 44593.1864323616, 'total_duration': 46187.8701505661, 'accumulated_submission_time': 44593.1864323616, 'accumulated_eval_time': 1486.2396006584167, 'accumulated_logging_time': 7.5586652755737305}
I0319 04:44:11.160754 139629739087616 logging_writer.py:48] [71596] accumulated_eval_time=1486.24, accumulated_logging_time=7.55867, accumulated_submission_time=44593.2, global_step=71596, preemption_count=0, score=44593.2, test/ctc_loss=0.1916, test/num_examples=2472, test/wer=0.0609957, total_duration=46187.9, train/ctc_loss=0.143779, train/wer=0.0516051, validation/ctc_loss=0.343934, validation/num_examples=5348, validation/wer=0.100623
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 05:08:13.423619 139649795105984 spec.py:321] Evaluating on the training split.
I0319 05:08:31.669056 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 05:08:51.837462 139649795105984 spec.py:349] Evaluating on the test split.
I0319 05:09:02.165051 139649795105984 submission_runner.py:469] Time since start: 47679.00s, 	Step: 73894, 	{'train/ctc_loss': 0.14137072711667387, 'train/wer': 0.05063970799594318, 'validation/ctc_loss': 0.34236031517785154, 'validation/wer': 0.10032346835320813, 'validation/num_examples': 5348, 'test/ctc_loss': 0.18998681508414927, 'test/wer': 0.05998009465196108, 'test/num_examples': 2472, 'score': 46032.030213832855, 'total_duration': 47679.00361919403, 'accumulated_submission_time': 46032.030213832855, 'accumulated_eval_time': 1534.9811301231384, 'accumulated_logging_time': 7.812559366226196}
I0319 05:09:02.313097 139629739087616 logging_writer.py:48] [73894] accumulated_eval_time=1534.98, accumulated_logging_time=7.81256, accumulated_submission_time=46032, global_step=73894, preemption_count=0, score=46032, test/ctc_loss=0.189987, test/num_examples=2472, test/wer=0.0599801, total_duration=47679, train/ctc_loss=0.141371, train/wer=0.0506397, validation/ctc_loss=0.34236, validation/num_examples=5348, validation/wer=0.100323
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 05:33:03.772378 139649795105984 spec.py:321] Evaluating on the training split.
I0319 05:33:20.028207 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 05:33:40.014565 139649795105984 spec.py:349] Evaluating on the test split.
I0319 05:33:50.280146 139649795105984 submission_runner.py:469] Time since start: 49167.12s, 	Step: 76182, 	{'train/ctc_loss': 0.13910770086268653, 'train/wer': 0.04970143344487773, 'validation/ctc_loss': 0.34038864688611375, 'validation/wer': 0.09946410466856563, 'validation/num_examples': 5348, 'test/ctc_loss': 0.18820113946786737, 'test/wer': 0.05969573253711941, 'test/num_examples': 2472, 'score': 47469.89224362373, 'total_duration': 49167.11873316765, 'accumulated_submission_time': 47469.89224362373, 'accumulated_eval_time': 1581.4891138076782, 'accumulated_logging_time': 8.093764543533325}
I0319 05:33:50.450843 139629739087616 logging_writer.py:48] [76182] accumulated_eval_time=1581.49, accumulated_logging_time=8.09376, accumulated_submission_time=47469.9, global_step=76182, preemption_count=0, score=47469.9, test/ctc_loss=0.188201, test/num_examples=2472, test/wer=0.0596957, total_duration=49167.1, train/ctc_loss=0.139108, train/wer=0.0497014, validation/ctc_loss=0.340389, validation/num_examples=5348, validation/wer=0.0994641
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 05:57:51.853201 139649795105984 spec.py:321] Evaluating on the training split.
I0319 05:58:06.799710 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 05:58:26.798948 139649795105984 spec.py:349] Evaluating on the test split.
I0319 05:58:37.158292 139649795105984 submission_runner.py:469] Time since start: 50654.00s, 	Step: 78504, 	{'train/ctc_loss': 0.13683608164011812, 'train/wer': 0.0491211133468199, 'validation/ctc_loss': 0.33841297451294744, 'validation/wer': 0.09842128132090958, 'validation/num_examples': 5348, 'test/ctc_loss': 0.18648290978656307, 'test/wer': 0.059066073568541426, 'test/num_examples': 2472, 'score': 48907.88532996178, 'total_duration': 50653.99679017067, 'accumulated_submission_time': 48907.88532996178, 'accumulated_eval_time': 1626.7940549850464, 'accumulated_logging_time': 8.5211763381958}
I0319 05:58:37.298676 139629739087616 logging_writer.py:48] [78504] accumulated_eval_time=1626.79, accumulated_logging_time=8.52118, accumulated_submission_time=48907.9, global_step=78504, preemption_count=0, score=48907.9, test/ctc_loss=0.186483, test/num_examples=2472, test/wer=0.0590661, total_duration=50654, train/ctc_loss=0.136836, train/wer=0.0491211, validation/ctc_loss=0.338413, validation/num_examples=5348, validation/wer=0.0984213
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 06:22:38.935685 139649795105984 spec.py:321] Evaluating on the training split.
I0319 06:22:54.728197 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 06:23:14.844963 139649795105984 spec.py:349] Evaluating on the test split.
I0319 06:23:25.349714 139649795105984 submission_runner.py:469] Time since start: 52142.19s, 	Step: 80842, 	{'train/ctc_loss': 0.13481425249040332, 'train/wer': 0.04875773534149397, 'validation/ctc_loss': 0.33628487847905847, 'validation/wer': 0.09715637522328972, 'validation/num_examples': 5348, 'test/ctc_loss': 0.18501639304653714, 'test/wer': 0.05904576198890988, 'test/num_examples': 2472, 'score': 50346.22521853447, 'total_duration': 52142.1882276535, 'accumulated_submission_time': 50346.22521853447, 'accumulated_eval_time': 1673.2080121040344, 'accumulated_logging_time': 8.83213996887207}
I0319 06:23:25.524721 139629739087616 logging_writer.py:48] [80842] accumulated_eval_time=1673.21, accumulated_logging_time=8.83214, accumulated_submission_time=50346.2, global_step=80842, preemption_count=0, score=50346.2, test/ctc_loss=0.185016, test/num_examples=2472, test/wer=0.0590458, total_duration=52142.2, train/ctc_loss=0.134814, train/wer=0.0487577, validation/ctc_loss=0.336285, validation/num_examples=5348, validation/wer=0.0971564
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 06:47:27.090521 139649795105984 spec.py:321] Evaluating on the training split.
I0319 06:47:39.995796 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 06:48:00.027630 139649795105984 spec.py:349] Evaluating on the test split.
I0319 06:48:10.454883 139649795105984 submission_runner.py:469] Time since start: 53627.29s, 	Step: 83183, 	{'train/ctc_loss': 0.13293905819163604, 'train/wer': 0.048155721034162956, 'validation/ctc_loss': 0.33483530334139616, 'validation/wer': 0.0964997827451359, 'validation/num_examples': 5348, 'test/ctc_loss': 0.1836820111891578, 'test/wer': 0.059370747263014646, 'test/num_examples': 2472, 'score': 51784.37153482437, 'total_duration': 53627.29341459274, 'accumulated_submission_time': 51784.37153482437, 'accumulated_eval_time': 1716.5722026824951, 'accumulated_logging_time': 9.184253454208374}
I0319 06:48:10.581699 139629739087616 logging_writer.py:48] [83183] accumulated_eval_time=1716.57, accumulated_logging_time=9.18425, accumulated_submission_time=51784.4, global_step=83183, preemption_count=0, score=51784.4, test/ctc_loss=0.183682, test/num_examples=2472, test/wer=0.0593707, total_duration=53627.3, train/ctc_loss=0.132939, train/wer=0.0481557, validation/ctc_loss=0.334835, validation/num_examples=5348, validation/wer=0.0964998
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 07:12:12.265457 139649795105984 spec.py:321] Evaluating on the training split.
I0319 07:12:25.823279 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 07:12:45.904556 139649795105984 spec.py:349] Evaluating on the test split.
I0319 07:12:56.211007 139649795105984 submission_runner.py:469] Time since start: 55113.05s, 	Step: 85519, 	{'train/ctc_loss': 0.13118776895595669, 'train/wer': 0.04757540093610513, 'validation/ctc_loss': 0.3333915390048315, 'validation/wer': 0.09557282865833051, 'validation/num_examples': 5348, 'test/ctc_loss': 0.1825725869644026, 'test/wer': 0.05847703775922654, 'test/num_examples': 2472, 'score': 53222.73074769974, 'total_duration': 55113.049458265305, 'accumulated_submission_time': 53222.73074769974, 'accumulated_eval_time': 1760.517798423767, 'accumulated_logging_time': 9.444705486297607}
I0319 07:12:56.403525 139629739087616 logging_writer.py:48] [85519] accumulated_eval_time=1760.52, accumulated_logging_time=9.44471, accumulated_submission_time=53222.7, global_step=85519, preemption_count=0, score=53222.7, test/ctc_loss=0.182573, test/num_examples=2472, test/wer=0.058477, total_duration=55113, train/ctc_loss=0.131188, train/wer=0.0475754, validation/ctc_loss=0.333392, validation/num_examples=5348, validation/wer=0.0955728
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 07:36:57.531154 139649795105984 spec.py:321] Evaluating on the training split.
I0319 07:37:11.335565 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 07:37:31.364861 139649795105984 spec.py:349] Evaluating on the test split.
I0319 07:37:41.790626 139649795105984 submission_runner.py:469] Time since start: 56598.63s, 	Step: 87830, 	{'train/ctc_loss': 0.12965745496914874, 'train/wer': 0.04670763256517754, 'validation/ctc_loss': 0.33239698865731626, 'validation/wer': 0.09555351711485541, 'validation/num_examples': 5348, 'test/ctc_loss': 0.18113315135880376, 'test/wer': 0.058761399874068206, 'test/num_examples': 2472, 'score': 54660.517416000366, 'total_duration': 56598.629160404205, 'accumulated_submission_time': 54660.517416000366, 'accumulated_eval_time': 1804.7772285938263, 'accumulated_logging_time': 9.779207229614258}
I0319 07:37:41.972594 139629739087616 logging_writer.py:48] [87830] accumulated_eval_time=1804.78, accumulated_logging_time=9.77921, accumulated_submission_time=54660.5, global_step=87830, preemption_count=0, score=54660.5, test/ctc_loss=0.181133, test/num_examples=2472, test/wer=0.0587614, total_duration=56598.6, train/ctc_loss=0.129657, train/wer=0.0467076, validation/ctc_loss=0.332397, validation/num_examples=5348, validation/wer=0.0955535
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 08:01:43.396307 139649795105984 spec.py:321] Evaluating on the training split.
I0319 08:02:05.518521 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 08:02:25.564029 139649795105984 spec.py:349] Evaluating on the test split.
I0319 08:02:35.925797 139649795105984 submission_runner.py:469] Time since start: 58092.76s, 	Step: 90129, 	{'train/ctc_loss': 0.12824927729306337, 'train/wer': 0.04605138273466355, 'validation/ctc_loss': 0.3311799920543399, 'validation/wer': 0.09522522087577849, 'validation/num_examples': 5348, 'test/ctc_loss': 0.18010547180774955, 'test/wer': 0.05859890723701582, 'test/num_examples': 2472, 'score': 56098.42741775513, 'total_duration': 58092.764308691025, 'accumulated_submission_time': 56098.42741775513, 'accumulated_eval_time': 1857.3066265583038, 'accumulated_logging_time': 10.138993740081787}
I0319 08:02:36.079730 139629739087616 logging_writer.py:48] [90129] accumulated_eval_time=1857.31, accumulated_logging_time=10.139, accumulated_submission_time=56098.4, global_step=90129, preemption_count=0, score=56098.4, test/ctc_loss=0.180105, test/num_examples=2472, test/wer=0.0585989, total_duration=58092.8, train/ctc_loss=0.128249, train/wer=0.0460514, validation/ctc_loss=0.33118, validation/num_examples=5348, validation/wer=0.0952252
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 08:26:37.682430 139649795105984 spec.py:321] Evaluating on the training split.
I0319 08:26:56.646790 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 08:27:16.805570 139649795105984 spec.py:349] Evaluating on the test split.
I0319 08:27:27.276810 139649795105984 submission_runner.py:469] Time since start: 59584.12s, 	Step: 92426, 	{'train/ctc_loss': 0.12687878460207613, 'train/wer': 0.04574766380483889, 'validation/ctc_loss': 0.3299142872656929, 'validation/wer': 0.09440448027808622, 'validation/num_examples': 5348, 'test/ctc_loss': 0.1787458885800172, 'test/wer': 0.05865984197591047, 'test/num_examples': 2472, 'score': 57536.63907289505, 'total_duration': 59584.11534833908, 'accumulated_submission_time': 57536.63907289505, 'accumulated_eval_time': 1906.9010574817657, 'accumulated_logging_time': 10.441392183303833}
I0319 08:27:27.451388 139629739087616 logging_writer.py:48] [92426] accumulated_eval_time=1906.9, accumulated_logging_time=10.4414, accumulated_submission_time=57536.6, global_step=92426, preemption_count=0, score=57536.6, test/ctc_loss=0.178746, test/num_examples=2472, test/wer=0.0586598, total_duration=59584.1, train/ctc_loss=0.126879, train/wer=0.0457477, validation/ctc_loss=0.329914, validation/num_examples=5348, validation/wer=0.0944045
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 08:51:28.824030 139649795105984 spec.py:321] Evaluating on the training split.
I0319 08:51:45.378433 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 08:52:05.713298 139649795105984 spec.py:349] Evaluating on the test split.
I0319 08:52:16.151716 139649795105984 submission_runner.py:469] Time since start: 61072.99s, 	Step: 94713, 	{'train/ctc_loss': 0.12565570554106292, 'train/wer': 0.04518361436373596, 'validation/ctc_loss': 0.3285528507497203, 'validation/wer': 0.09402790518032153, 'validation/num_examples': 5348, 'test/ctc_loss': 0.1773912052706379, 'test/wer': 0.05805049458696403, 'test/num_examples': 2472, 'score': 58974.45537567139, 'total_duration': 61072.9902510643, 'accumulated_submission_time': 58974.45537567139, 'accumulated_eval_time': 1954.2286972999573, 'accumulated_logging_time': 10.805955410003662}
I0319 08:52:16.241870 139629739087616 logging_writer.py:48] [94713] accumulated_eval_time=1954.23, accumulated_logging_time=10.806, accumulated_submission_time=58974.5, global_step=94713, preemption_count=0, score=58974.5, test/ctc_loss=0.177391, test/num_examples=2472, test/wer=0.0580505, total_duration=61073, train/ctc_loss=0.125656, train/wer=0.0451836, validation/ctc_loss=0.328553, validation/num_examples=5348, validation/wer=0.0940279
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 09:16:17.508313 139649795105984 spec.py:321] Evaluating on the training split.
I0319 09:16:32.435375 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 09:16:52.605833 139649795105984 spec.py:349] Evaluating on the test split.
I0319 09:17:03.175924 139649795105984 submission_runner.py:469] Time since start: 62560.01s, 	Step: 97030, 	{'train/ctc_loss': 0.12437644879298226, 'train/wer': 0.04481481280609173, 'validation/ctc_loss': 0.32715327779965375, 'validation/wer': 0.09321682035436682, 'validation/num_examples': 5348, 'test/ctc_loss': 0.17620836999291004, 'test/wer': 0.057705197733227714, 'test/num_examples': 2472, 'score': 60412.41719031334, 'total_duration': 62560.01437973976, 'accumulated_submission_time': 60412.41719031334, 'accumulated_eval_time': 1999.8961629867554, 'accumulated_logging_time': 11.050316572189331}
I0319 09:17:03.283042 139629739087616 logging_writer.py:48] [97030] accumulated_eval_time=1999.9, accumulated_logging_time=11.0503, accumulated_submission_time=60412.4, global_step=97030, preemption_count=0, score=60412.4, test/ctc_loss=0.176208, test/num_examples=2472, test/wer=0.0577052, total_duration=62560, train/ctc_loss=0.124376, train/wer=0.0448148, validation/ctc_loss=0.327153, validation/num_examples=5348, validation/wer=0.0932168
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 09:41:04.921481 139649795105984 spec.py:321] Evaluating on the training split.
I0319 09:41:19.862710 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 09:41:40.046317 139649795105984 spec.py:349] Evaluating on the test split.
I0319 09:41:50.504293 139649795105984 submission_runner.py:469] Time since start: 64047.34s, 	Step: 99367, 	{'train/ctc_loss': 0.12340004468871647, 'train/wer': 0.044446011248447506, 'validation/ctc_loss': 0.32624659750739093, 'validation/wer': 0.09293680297397769, 'validation/num_examples': 5348, 'test/ctc_loss': 0.17516230634921146, 'test/wer': 0.0573192777202283, 'test/num_examples': 2472, 'score': 61850.82379865646, 'total_duration': 64047.34280371666, 'accumulated_submission_time': 61850.82379865646, 'accumulated_eval_time': 2045.4788448810577, 'accumulated_logging_time': 11.258867740631104}
I0319 09:41:50.716114 139629739087616 logging_writer.py:48] [99367] accumulated_eval_time=2045.48, accumulated_logging_time=11.2589, accumulated_submission_time=61850.8, global_step=99367, preemption_count=0, score=61850.8, test/ctc_loss=0.175162, test/num_examples=2472, test/wer=0.0573193, total_duration=64047.3, train/ctc_loss=0.1234, train/wer=0.044446, validation/ctc_loss=0.326247, validation/num_examples=5348, validation/wer=0.0929368
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 10:05:52.121735 139649795105984 spec.py:321] Evaluating on the training split.
I0319 10:06:05.509042 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 10:06:25.578259 139649795105984 spec.py:349] Evaluating on the test split.
I0319 10:06:35.847234 139649795105984 submission_runner.py:469] Time since start: 65532.69s, 	Step: 101708, 	{'train/ctc_loss': 0.12219850744755623, 'train/wer': 0.04387111470270798, 'validation/ctc_loss': 0.3249418773399461, 'validation/wer': 0.09262781827837589, 'validation/num_examples': 5348, 'test/ctc_loss': 0.17428889276983586, 'test/wer': 0.05666930717201877, 'test/num_examples': 2472, 'score': 63288.85478377342, 'total_duration': 65532.685730695724, 'accumulated_submission_time': 63288.85478377342, 'accumulated_eval_time': 2089.204220533371, 'accumulated_logging_time': 11.641066551208496}
I0319 10:06:35.929063 139629739087616 logging_writer.py:48] [101708] accumulated_eval_time=2089.2, accumulated_logging_time=11.6411, accumulated_submission_time=63288.9, global_step=101708, preemption_count=0, score=63288.9, test/ctc_loss=0.174289, test/num_examples=2472, test/wer=0.0566693, total_duration=65532.7, train/ctc_loss=0.122199, train/wer=0.0438711, validation/ctc_loss=0.324942, validation/num_examples=5348, validation/wer=0.0926278
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 10:30:37.279128 139649795105984 spec.py:321] Evaluating on the training split.
I0319 10:30:50.948722 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 10:31:11.407500 139649795105984 spec.py:349] Evaluating on the test split.
I0319 10:31:21.710983 139649795105984 submission_runner.py:469] Time since start: 67018.55s, 	Step: 104049, 	{'train/ctc_loss': 0.12097025412589209, 'train/wer': 0.04314435869205612, 'validation/ctc_loss': 0.3234175674873276, 'validation/wer': 0.09174914305025829, 'validation/num_examples': 5348, 'test/ctc_loss': 0.173285838128152, 'test/wer': 0.05632401031828245, 'test/num_examples': 2472, 'score': 64726.72796320915, 'total_duration': 67018.54951763153, 'accumulated_submission_time': 64726.72796320915, 'accumulated_eval_time': 2133.636000394821, 'accumulated_logging_time': 11.911903619766235}
I0319 10:31:21.837270 139629739087616 logging_writer.py:48] [104049] accumulated_eval_time=2133.64, accumulated_logging_time=11.9119, accumulated_submission_time=64726.7, global_step=104049, preemption_count=0, score=64726.7, test/ctc_loss=0.173286, test/num_examples=2472, test/wer=0.056324, total_duration=67018.5, train/ctc_loss=0.12097, train/wer=0.0431444, validation/ctc_loss=0.323418, validation/num_examples=5348, validation/wer=0.0917491
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 10:55:23.033940 139649795105984 spec.py:321] Evaluating on the training split.
I0319 10:55:36.916888 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 10:55:56.904655 139649795105984 spec.py:349] Evaluating on the test split.
I0319 10:56:07.227949 139649795105984 submission_runner.py:469] Time since start: 68504.07s, 	Step: 106359, 	{'train/ctc_loss': 0.11981998430403872, 'train/wer': 0.04246641465226894, 'validation/ctc_loss': 0.3217662989552668, 'validation/wer': 0.09107323902862936, 'validation/num_examples': 5348, 'test/ctc_loss': 0.17243429247083808, 'test/wer': 0.05626307557938781, 'test/num_examples': 2472, 'score': 66164.6469900608, 'total_duration': 68504.06647658348, 'accumulated_submission_time': 66164.6469900608, 'accumulated_eval_time': 2177.830010175705, 'accumulated_logging_time': 12.179038047790527}
I0319 10:56:07.422255 139629739087616 logging_writer.py:48] [106359] accumulated_eval_time=2177.83, accumulated_logging_time=12.179, accumulated_submission_time=66164.6, global_step=106359, preemption_count=0, score=66164.6, test/ctc_loss=0.172434, test/num_examples=2472, test/wer=0.0562631, total_duration=68504.1, train/ctc_loss=0.11982, train/wer=0.0424664, validation/ctc_loss=0.321766, validation/num_examples=5348, validation/wer=0.0910732
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 11:20:08.930046 139649795105984 spec.py:321] Evaluating on the training split.
I0319 11:20:30.858281 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 11:20:51.169045 139649795105984 spec.py:349] Evaluating on the test split.
I0319 11:21:01.542231 139649795105984 submission_runner.py:469] Time since start: 69998.38s, 	Step: 108660, 	{'train/ctc_loss': 0.11883176651792955, 'train/wer': 0.04253692083240681, 'validation/ctc_loss': 0.3200625867225441, 'validation/wer': 0.09062907352870178, 'validation/num_examples': 5348, 'test/ctc_loss': 0.17181059928282238, 'test/wer': 0.05575528608859911, 'test/num_examples': 2472, 'score': 67602.55174350739, 'total_duration': 69998.38077425957, 'accumulated_submission_time': 67602.55174350739, 'accumulated_eval_time': 2230.4421541690826, 'accumulated_logging_time': 12.512118816375732}
I0319 11:21:01.748216 139629739087616 logging_writer.py:48] [108660] accumulated_eval_time=2230.44, accumulated_logging_time=12.5121, accumulated_submission_time=67602.6, global_step=108660, preemption_count=0, score=67602.6, test/ctc_loss=0.171811, test/num_examples=2472, test/wer=0.0557553, total_duration=69998.4, train/ctc_loss=0.118832, train/wer=0.0425369, validation/ctc_loss=0.320063, validation/num_examples=5348, validation/wer=0.0906291
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 11:45:03.411239 139649795105984 spec.py:321] Evaluating on the training split.
I0319 11:45:23.795107 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 11:45:43.986333 139649795105984 spec.py:349] Evaluating on the test split.
I0319 11:45:54.361051 139649795105984 submission_runner.py:469] Time since start: 71491.20s, 	Step: 110956, 	{'train/ctc_loss': 0.11776329489315257, 'train/wer': 0.04211930730389791, 'validation/ctc_loss': 0.3187776183958048, 'validation/wer': 0.09046492540916333, 'validation/num_examples': 5348, 'test/ctc_loss': 0.17100523316292812, 'test/wer': 0.05549123555338899, 'test/num_examples': 2472, 'score': 69040.79412078857, 'total_duration': 71491.19953751564, 'accumulated_submission_time': 69040.79412078857, 'accumulated_eval_time': 2281.3919122219086, 'accumulated_logging_time': 12.934014797210693}
I0319 11:45:54.600151 139629739087616 logging_writer.py:48] [110956] accumulated_eval_time=2281.39, accumulated_logging_time=12.934, accumulated_submission_time=69040.8, global_step=110956, preemption_count=0, score=69040.8, test/ctc_loss=0.171005, test/num_examples=2472, test/wer=0.0554912, total_duration=71491.2, train/ctc_loss=0.117763, train/wer=0.0421193, validation/ctc_loss=0.318778, validation/num_examples=5348, validation/wer=0.0904649
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 12:09:56.431308 139649795105984 spec.py:321] Evaluating on the training split.
I0319 12:10:12.688507 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 12:10:32.718211 139649795105984 spec.py:349] Evaluating on the test split.
I0319 12:10:43.207929 139649795105984 submission_runner.py:469] Time since start: 72980.05s, 	Step: 113248, 	{'train/ctc_loss': 0.11680207038008218, 'train/wer': 0.041739658641617085, 'validation/ctc_loss': 0.3176919263655285, 'validation/wer': 0.09001110413749819, 'validation/num_examples': 5348, 'test/ctc_loss': 0.17011666868511555, 'test/wer': 0.05500375764223184, 'test/num_examples': 2472, 'score': 70478.99426484108, 'total_duration': 72980.04655075073, 'accumulated_submission_time': 70478.99426484108, 'accumulated_eval_time': 2328.1686317920685, 'accumulated_logging_time': 13.298274278640747}
I0319 12:10:43.377532 139629739087616 logging_writer.py:48] [113248] accumulated_eval_time=2328.17, accumulated_logging_time=13.2983, accumulated_submission_time=70479, global_step=113248, preemption_count=0, score=70479, test/ctc_loss=0.170117, test/num_examples=2472, test/wer=0.0550038, total_duration=72980, train/ctc_loss=0.116802, train/wer=0.0417397, validation/ctc_loss=0.317692, validation/num_examples=5348, validation/wer=0.0900111
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 12:34:44.926366 139649795105984 spec.py:321] Evaluating on the training split.
I0319 12:34:59.628814 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 12:35:19.661155 139649795105984 spec.py:349] Evaluating on the test split.
I0319 12:35:30.076582 139649795105984 submission_runner.py:469] Time since start: 74466.92s, 	Step: 115559, 	{'train/ctc_loss': 0.11606410465438473, 'train/wer': 0.04145221036874732, 'validation/ctc_loss': 0.31666024060427644, 'validation/wer': 0.08938347897455703, 'validation/num_examples': 5348, 'test/ctc_loss': 0.1694133361591618, 'test/wer': 0.055024069221863384, 'test/num_examples': 2472, 'score': 71917.2119679451, 'total_duration': 74466.91516327858, 'accumulated_submission_time': 71917.2119679451, 'accumulated_eval_time': 2373.3188951015472, 'accumulated_logging_time': 13.641619443893433}
I0319 12:35:30.214092 139629739087616 logging_writer.py:48] [115559] accumulated_eval_time=2373.32, accumulated_logging_time=13.6416, accumulated_submission_time=71917.2, global_step=115559, preemption_count=0, score=71917.2, test/ctc_loss=0.169413, test/num_examples=2472, test/wer=0.0550241, total_duration=74466.9, train/ctc_loss=0.116064, train/wer=0.0414522, validation/ctc_loss=0.31666, validation/num_examples=5348, validation/wer=0.0893835
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 12:59:31.396337 139649795105984 spec.py:321] Evaluating on the training split.
I0319 12:59:45.878402 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 13:00:06.347093 139649795105984 spec.py:349] Evaluating on the test split.
I0319 13:00:16.775419 139649795105984 submission_runner.py:469] Time since start: 75953.61s, 	Step: 117897, 	{'train/ctc_loss': 0.11512708828935986, 'train/wer': 0.04122442117137883, 'validation/ctc_loss': 0.3154668534326502, 'validation/wer': 0.08898759233331724, 'validation/num_examples': 5348, 'test/ctc_loss': 0.1686593126620106, 'test/wer': 0.05463814920886397, 'test/num_examples': 2472, 'score': 73355.18144106865, 'total_duration': 75953.61403274536, 'accumulated_submission_time': 73355.18144106865, 'accumulated_eval_time': 2418.6980226039886, 'accumulated_logging_time': 13.894997358322144}
I0319 13:00:16.987016 139629739087616 logging_writer.py:48] [117897] accumulated_eval_time=2418.7, accumulated_logging_time=13.895, accumulated_submission_time=73355.2, global_step=117897, preemption_count=0, score=73355.2, test/ctc_loss=0.168659, test/num_examples=2472, test/wer=0.0546381, total_duration=75953.6, train/ctc_loss=0.115127, train/wer=0.0412244, validation/ctc_loss=0.315467, validation/num_examples=5348, validation/wer=0.0889876
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 13:24:18.149246 139649795105984 spec.py:321] Evaluating on the training split.
I0319 13:24:31.337335 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 13:24:51.344170 139649795105984 spec.py:349] Evaluating on the test split.
I0319 13:25:01.831060 139649795105984 submission_runner.py:469] Time since start: 77438.67s, 	Step: 120235, 	{'train/ctc_loss': 0.1142781267529128, 'train/wer': 0.040904431584599284, 'validation/ctc_loss': 0.31480952486983804, 'validation/wer': 0.08897793656157968, 'validation/num_examples': 5348, 'test/ctc_loss': 0.16756214449901832, 'test/wer': 0.05372412812544432, 'test/num_examples': 2472, 'score': 74792.97836208344, 'total_duration': 77438.66947722435, 'accumulated_submission_time': 74792.97836208344, 'accumulated_eval_time': 2462.3795931339264, 'accumulated_logging_time': 14.33096432685852}
I0319 13:25:01.936240 139629739087616 logging_writer.py:48] [120235] accumulated_eval_time=2462.38, accumulated_logging_time=14.331, accumulated_submission_time=74793, global_step=120235, preemption_count=0, score=74793, test/ctc_loss=0.167562, test/num_examples=2472, test/wer=0.0537241, total_duration=77438.7, train/ctc_loss=0.114278, train/wer=0.0409044, validation/ctc_loss=0.31481, validation/num_examples=5348, validation/wer=0.0889779
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 13:49:03.182573 139649795105984 spec.py:321] Evaluating on the training split.
I0319 13:49:17.167037 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 13:49:37.148076 139649795105984 spec.py:349] Evaluating on the test split.
I0319 13:49:47.539391 139649795105984 submission_runner.py:469] Time since start: 78924.38s, 	Step: 122579, 	{'train/ctc_loss': 0.11333742768706748, 'train/wer': 0.04058986555013803, 'validation/ctc_loss': 0.3139762608754758, 'validation/wer': 0.08898759233331724, 'validation/num_examples': 5348, 'test/ctc_loss': 0.1665439765541789, 'test/wer': 0.05378506286433896, 'test/num_examples': 2472, 'score': 76230.93557953835, 'total_duration': 78924.37789106369, 'accumulated_submission_time': 76230.93557953835, 'accumulated_eval_time': 2506.736315011978, 'accumulated_logging_time': 14.57935619354248}
I0319 13:49:47.704635 139629739087616 logging_writer.py:48] [122579] accumulated_eval_time=2506.74, accumulated_logging_time=14.5794, accumulated_submission_time=76230.9, global_step=122579, preemption_count=0, score=76230.9, test/ctc_loss=0.166544, test/num_examples=2472, test/wer=0.0537851, total_duration=78924.4, train/ctc_loss=0.113337, train/wer=0.0405899, validation/ctc_loss=0.313976, validation/num_examples=5348, validation/wer=0.0889876
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 14:13:49.300599 139649795105984 spec.py:321] Evaluating on the training split.
I0319 14:14:03.324331 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 14:14:23.261305 139649795105984 spec.py:349] Evaluating on the test split.
I0319 14:14:33.617778 139649795105984 submission_runner.py:469] Time since start: 80410.46s, 	Step: 124890, 	{'train/ctc_loss': 0.11241768965671632, 'train/wer': 0.04026987596335848, 'validation/ctc_loss': 0.3130101297400511, 'validation/wer': 0.08863032877902767, 'validation/num_examples': 5348, 'test/ctc_loss': 0.16579837440007955, 'test/wer': 0.05309446915686633, 'test/num_examples': 2472, 'score': 77669.28788089752, 'total_duration': 80410.45634627342, 'accumulated_submission_time': 77669.28788089752, 'accumulated_eval_time': 2551.053557395935, 'accumulated_logging_time': 14.8559250831604}
I0319 14:14:33.865233 139629739087616 logging_writer.py:48] [124890] accumulated_eval_time=2551.05, accumulated_logging_time=14.8559, accumulated_submission_time=77669.3, global_step=124890, preemption_count=0, score=77669.3, test/ctc_loss=0.165798, test/num_examples=2472, test/wer=0.0530945, total_duration=80410.5, train/ctc_loss=0.112418, train/wer=0.0402699, validation/ctc_loss=0.31301, validation/num_examples=5348, validation/wer=0.0886303
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 14:38:36.005727 139649795105984 spec.py:321] Evaluating on the training split.
I0319 14:38:56.778172 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 14:39:16.928085 139649795105984 spec.py:349] Evaluating on the test split.
I0319 14:39:27.418007 139649795105984 submission_runner.py:469] Time since start: 81904.26s, 	Step: 127191, 	{'train/ctc_loss': 0.11155208336853238, 'train/wer': 0.039819721120939795, 'validation/ctc_loss': 0.3118456744982593, 'validation/wer': 0.08833099985516342, 'validation/num_examples': 5348, 'test/ctc_loss': 0.16472532987603783, 'test/wer': 0.052850730201287756, 'test/num_examples': 2472, 'score': 79108.1527607441, 'total_duration': 81904.25654053688, 'accumulated_submission_time': 79108.1527607441, 'accumulated_eval_time': 2602.4657742977142, 'accumulated_logging_time': 15.245776653289795}
I0319 14:39:27.630732 139629739087616 logging_writer.py:48] [127191] accumulated_eval_time=2602.47, accumulated_logging_time=15.2458, accumulated_submission_time=79108.2, global_step=127191, preemption_count=0, score=79108.2, test/ctc_loss=0.164725, test/num_examples=2472, test/wer=0.0528507, total_duration=81904.3, train/ctc_loss=0.111552, train/wer=0.0398197, validation/ctc_loss=0.311846, validation/num_examples=5348, validation/wer=0.088331
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 15:03:29.234588 139649795105984 spec.py:321] Evaluating on the training split.
I0319 15:03:49.336795 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 15:04:09.585185 139649795105984 spec.py:349] Evaluating on the test split.
I0319 15:04:19.899470 139649795105984 submission_runner.py:469] Time since start: 83396.74s, 	Step: 129488, 	{'train/ctc_loss': 0.11088205621316771, 'train/wer': 0.03965701455139087, 'validation/ctc_loss': 0.31065087124905466, 'validation/wer': 0.08801235938782408, 'validation/num_examples': 5348, 'test/ctc_loss': 0.16402006745896802, 'test/wer': 0.05232262913086751, 'test/num_examples': 2472, 'score': 80546.35296678543, 'total_duration': 83396.73790407181, 'accumulated_submission_time': 80546.35296678543, 'accumulated_eval_time': 2653.1305940151215, 'accumulated_logging_time': 15.6360764503479}
I0319 15:04:20.071826 139629739087616 logging_writer.py:48] [129488] accumulated_eval_time=2653.13, accumulated_logging_time=15.6361, accumulated_submission_time=80546.4, global_step=129488, preemption_count=0, score=80546.4, test/ctc_loss=0.16402, test/num_examples=2472, test/wer=0.0523226, total_duration=83396.7, train/ctc_loss=0.110882, train/wer=0.039657, validation/ctc_loss=0.310651, validation/num_examples=5348, validation/wer=0.0880124
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 15:28:21.968191 139649795105984 spec.py:321] Evaluating on the training split.
I0319 15:28:38.474411 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 15:28:58.724664 139649795105984 spec.py:349] Evaluating on the test split.
I0319 15:29:09.083086 139649795105984 submission_runner.py:469] Time since start: 84885.92s, 	Step: 131779, 	{'train/ctc_loss': 0.10999067761906291, 'train/wer': 0.03915262418578921, 'validation/ctc_loss': 0.3094447637943535, 'validation/wer': 0.08748129194225848, 'validation/num_examples': 5348, 'test/ctc_loss': 0.16330533103096487, 'test/wer': 0.05252574492718299, 'test/num_examples': 2472, 'score': 81984.84538173676, 'total_duration': 84885.9215991497, 'accumulated_submission_time': 81984.84538173676, 'accumulated_eval_time': 2700.2453854084015, 'accumulated_logging_time': 15.917577981948853}
I0319 15:29:09.257484 139629739087616 logging_writer.py:48] [131779] accumulated_eval_time=2700.25, accumulated_logging_time=15.9176, accumulated_submission_time=81984.8, global_step=131779, preemption_count=0, score=81984.8, test/ctc_loss=0.163305, test/num_examples=2472, test/wer=0.0525257, total_duration=84885.9, train/ctc_loss=0.109991, train/wer=0.0391526, validation/ctc_loss=0.309445, validation/num_examples=5348, validation/wer=0.0874813
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 15:53:10.519278 139649795105984 spec.py:321] Evaluating on the training split.
I0319 15:53:26.136178 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 15:53:46.360113 139649795105984 spec.py:349] Evaluating on the test split.
I0319 15:53:56.694116 139649795105984 submission_runner.py:469] Time since start: 86373.53s, 	Step: 134088, 	{'train/ctc_loss': 0.10923512336704558, 'train/wer': 0.038962799854648796, 'validation/ctc_loss': 0.3080096668291738, 'validation/wer': 0.08724955342055714, 'validation/num_examples': 5348, 'test/ctc_loss': 0.16251427618155453, 'test/wer': 0.051977332277131194, 'test/num_examples': 2472, 'score': 83422.81868338585, 'total_duration': 86373.53265142441, 'accumulated_submission_time': 83422.81868338585, 'accumulated_eval_time': 2746.420201778412, 'accumulated_logging_time': 16.25924825668335}
I0319 15:53:56.858350 139629739087616 logging_writer.py:48] [134088] accumulated_eval_time=2746.42, accumulated_logging_time=16.2592, accumulated_submission_time=83422.8, global_step=134088, preemption_count=0, score=83422.8, test/ctc_loss=0.162514, test/num_examples=2472, test/wer=0.0519773, total_duration=86373.5, train/ctc_loss=0.109235, train/wer=0.0389628, validation/ctc_loss=0.30801, validation/num_examples=5348, validation/wer=0.0872496
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 16:17:58.156967 139649795105984 spec.py:321] Evaluating on the training split.
I0319 16:18:12.725053 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 16:18:32.884329 139649795105984 spec.py:349] Evaluating on the test split.
I0319 16:18:43.324370 139649795105984 submission_runner.py:469] Time since start: 87860.16s, 	Step: 136417, 	{'train/ctc_loss': 0.10851854106546686, 'train/wer': 0.03869162223873392, 'validation/ctc_loss': 0.30715467336852237, 'validation/wer': 0.08696953604016801, 'validation/num_examples': 5348, 'test/ctc_loss': 0.16184674689533152, 'test/wer': 0.05140860804744785, 'test/num_examples': 2472, 'score': 84860.81177997589, 'total_duration': 87860.16287302971, 'accumulated_submission_time': 84860.81177997589, 'accumulated_eval_time': 2791.587429046631, 'accumulated_logging_time': 16.542335271835327}
I0319 16:18:43.472207 139629739087616 logging_writer.py:48] [136417] accumulated_eval_time=2791.59, accumulated_logging_time=16.5423, accumulated_submission_time=84860.8, global_step=136417, preemption_count=0, score=84860.8, test/ctc_loss=0.161847, test/num_examples=2472, test/wer=0.0514086, total_duration=87860.2, train/ctc_loss=0.108519, train/wer=0.0386916, validation/ctc_loss=0.307155, validation/num_examples=5348, validation/wer=0.0869695
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 16:42:44.773082 139649795105984 spec.py:321] Evaluating on the training split.
I0319 16:42:57.972045 139649795105984 spec.py:333] Evaluating on the validation split.
I0319 16:43:17.970766 139649795105984 spec.py:349] Evaluating on the test split.
I0319 16:43:28.268505 139649795105984 submission_runner.py:469] Time since start: 89345.11s, 	Step: 138747, 	{'train/ctc_loss': 0.10778526121357321, 'train/wer': 0.03839332686122757, 'validation/ctc_loss': 0.30595183754132993, 'validation/wer': 0.08674745329020422, 'validation/num_examples': 5348, 'test/ctc_loss': 0.16110382653797786, 'test/wer': 0.05112424593260618, 'test/num_examples': 2472, 'score': 86298.80665063858, 'total_duration': 89345.10709571838, 'accumulated_submission_time': 86298.80665063858, 'accumulated_eval_time': 2835.0828409194946, 'accumulated_logging_time': 16.81837558746338}
I0319 16:43:28.336623 139629739087616 logging_writer.py:48] [138747] accumulated_eval_time=2835.08, accumulated_logging_time=16.8184, accumulated_submission_time=86298.8, global_step=138747, preemption_count=0, score=86298.8, test/ctc_loss=0.161104, test/num_examples=2472, test/wer=0.0511242, total_duration=89345.1, train/ctc_loss=0.107785, train/wer=0.0383933, validation/ctc_loss=0.305952, validation/num_examples=5348, validation/wer=0.0867475
/usr/local/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
I0319 17:07:28.969042 139629739087616 logging_writer.py:48] [141090] global_step=141090, preemption_count=0, score=87737.1
I0319 17:07:30.402197 139649795105984 submission_runner.py:750] Final librispeech_conformer score: 87737.11081194878
